#!/usr/bin/env python3
"""
Render a week pack JSON file into LaTeX content files.

Supports two question formats:
  - MCQ:       questionText, options, correctAnswer, explanation  (week*.sample.json)
  - Bilingual: question.en/zh, answer, solution, common_mistake   (week*.json)

Input:  _data/content/week{nn}.json (or week{nn}.sample.json)
Output: build/week_pack_vars.tex   (variable definitions)
        build/week_pack_content.tex (questions, solutions, vocab, checklist)

Usage:
    python3 tools/week_pack/render_week_pack.py _data/content/week01.json
    python3 tools/week_pack/render_week_pack.py _data/content/week01.json --lang en
    python3 tools/week_pack/render_week_pack.py _data/content/week01.json --lang bilingual
"""

import argparse
import json
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BUILD_DIR = os.path.join(REPO_ROOT, "build")


# ── Format detection ────────────────────────────────────────────────────────

def is_bilingual(question):
    """Return True if question uses bilingual open-ended format."""
    return isinstance(question.get("question"), dict)


# ── Text helpers ────────────────────────────────────────────────────────────

def tex_escape(text):
    """Escape special LaTeX characters in plain text."""
    if not text:
        return ""
    replacements = [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def math_to_latex(text):
    """Convert backtick-wrapped math to LaTeX inline math.

    Input:  "Simplify `4a + 5a - 2a`."
    Output: "Simplify $4a + 5a - 2a$."

    Also handles dollar-sign math expressions like "$12.60" by preserving
    currency amounts (digits after $) while converting algebraic $ to math.
    """
    if not text:
        return ""
    # If text has backtick-wrapped math, process those
    if "`" in text:
        parts = re.split(r'`([^`]+)`', text)
        result = []
        for i, part in enumerate(parts):
            if i % 2 == 0:
                result.append(tex_escape(part))
            else:
                result.append(f"${part}$")
        return "".join(result)
    # Otherwise just escape
    return tex_escape(text)


def get_question_text(q):
    """Extract English question text from either format."""
    if is_bilingual(q):
        return q["question"].get("en", "")
    return q.get("questionText", "")


def get_marks(q):
    """Get marks value — bilingual format may estimate from solution steps."""
    if "marks" in q:
        return q["marks"]
    # Estimate: 1 mark per solution step (capped at 6)
    if is_bilingual(q):
        sol = q.get("solution", {})
        steps = sol.get("en", []) if isinstance(sol, dict) else []
        return min(len(steps), 6) if steps else 2
    return 0


# ── Variable file ───────────────────────────────────────────────────────────

def render_vars(data, out_path, lang="bilingual"):
    """Generate week_pack_vars.tex with document-level variables."""
    week_num = str(data.get("week_number", 1)).zfill(2)
    topic = tex_escape(data.get("topic", ""))
    board = tex_escape(data.get("board", "CIE 0580"))
    version = tex_escape(data.get("version", "v1"))

    core_q = data.get("questions_core", [])
    ext_q = data.get("questions_extended", [])
    total_marks = sum(get_marks(q) for q in core_q + ext_q)

    if lang == "bilingual":
        edition = r"Bilingual Edition \begin{CJK}{UTF8}{} 双语版\end{CJK}"
        edition = "Bilingual Edition 双语版"
    else:
        edition = "English Edition"

    lines = [
        f"\\renewcommand{{\\weeknum}}{{{week_num}}}",
        f"\\renewcommand{{\\weektopic}}{{{topic}}}",
        f"\\renewcommand{{\\weekboard}}{{{board}}}",
        f"\\renewcommand{{\\weekversion}}{{{version}}}",
        f"\\renewcommand{{\\weekdate}}{{2026}}",
        f"\\renewcommand{{\\weektotalmarks}}{{{total_marks}}}",
        f"\\renewcommand{{\\weekcorecount}}{{{len(core_q)}}}",
        f"\\renewcommand{{\\weekextcount}}{{{len(ext_q)}}}",
        f"\\renewcommand{{\\weekedition}}{{{edition}}}",
    ]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("% Auto-generated by render_week_pack.py — do not edit\n")
        f.write("\n".join(lines) + "\n")


# ── Questions rendering ─────────────────────────────────────────────────────

def render_questions(questions, lines, start_num=1, section="core",
                     show_zh=True):
    """Render a question list (auto-detects MCQ vs bilingual)."""
    for i, q in enumerate(questions):
        num = start_num + i
        marks_val = get_marks(q)

        lines.append(r"\needspace{4\baselineskip}")

        if is_bilingual(q):
            _render_bilingual_question(q, num, marks_val, lines, section,
                                       show_zh=show_zh)
        else:
            _render_mcq_question(q, num, marks_val, lines)


def _render_bilingual_question(q, num, marks_val, lines, section="core",
                                show_zh=True):
    """Render one bilingual open-ended question with working space."""
    q_en = q["question"].get("en", "")
    q_zh = q["question"].get("zh", "")

    marks_str = f"\\qmarks{{{marks_val}}}" if marks_val > 0 else ""

    # Question header: circled number (purple for core, blue for extended) + marks
    cmd = "\\qnumext" if section == "extended" else "\\qnum"
    lines.append(f"\\noindent{cmd}{{{num}}}\\hspace{{2mm}}{marks_str}")
    lines.append("")

    # English question text
    lines.append(f"\\noindent {math_to_latex(q_en)}")
    lines.append("")

    # Chinese translation (smaller, gray) — only in bilingual mode
    if show_zh and q_zh:
        lines.append(f"{{\\small\\color{{gray}}{math_to_latex(q_zh)}}}")
        lines.append("")

    # Answer box — height scales with marks/difficulty
    if marks_val <= 2:
        height = "1.3cm"
    elif marks_val <= 4:
        height = "2.5cm"
    else:
        height = "4.0cm"
    lines.append(f"\\AnswerBox[{height}]")
    lines.append(r"\vspace{3mm}")
    lines.append("")


def _render_mcq_question(q, num, marks_val, lines):
    """Render one multiple-choice question."""
    question_text = math_to_latex(q.get("questionText", ""))
    marks_str = f"\\qmarks{{{marks_val}}}" if marks_val > 0 else ""

    lines.append(f"\\textbf{{Question {num}}} {marks_str}")
    lines.append("")
    lines.append(question_text)
    lines.append("")

    options = q.get("options", [])
    if options:
        lines.append(r"\begin{enumerate}[label=\textbf{\Alph*.}, "
                      r"leftmargin=10mm, itemsep=1mm]")
        for opt in options:
            lines.append(f"  \\item {math_to_latex(opt)}")
        lines.append(r"\end{enumerate}")
        lines.append("")

    lines.append(r"\vspace{2mm}")
    lines.append("")


# ── Solutions rendering ─────────────────────────────────────────────────────

def render_solutions(questions, lines, start_num=1, show_zh=True):
    """Render solutions for a question list (auto-detects format)."""
    for i, q in enumerate(questions):
        num = start_num + i

        lines.append(r"\needspace{3\baselineskip}")

        if is_bilingual(q):
            _render_bilingual_solution(q, num, lines, show_zh=show_zh)
        else:
            _render_mcq_solution(q, num, lines)

        if i < len(questions) - 1:
            lines.append(r"\solutionsep")


def _render_bilingual_solution(q, num, lines, show_zh=True):
    """Render compact step-by-step solution for a bilingual question."""
    answer = q.get("answer", {})
    solution = q.get("solution", {})
    mistake = q.get("common_mistake", {})

    ans_en = answer.get("en", "") if isinstance(answer, dict) else str(answer)
    sol_steps_en = solution.get("en", []) if isinstance(solution, dict) else []
    sol_steps_zh = solution.get("zh", []) if isinstance(solution, dict) else []
    mistake_en = mistake.get("en", "") if isinstance(mistake, dict) else str(mistake) if mistake else ""
    mistake_zh = mistake.get("zh", "") if isinstance(mistake, dict) else ""

    # Compact: Q number + answer on same line, then steps below
    lines.append(f"\\noindent\\textbf{{\\sffamily Q{num}.}}"
                 f" \\textbf{{{math_to_latex(ans_en)}}}" if ans_en else
                 f"\\noindent\\textbf{{\\sffamily Q{num}.}}")
    lines.append("")

    # Step-by-step solution (smaller text for compactness)
    if sol_steps_en:
        lines.append(r"{\small")
        lines.append(r"\begin{enumerate}[label=\arabic*., leftmargin=8mm, itemsep=0pt, topsep=2pt]")
        for j, step in enumerate(sol_steps_en):
            lines.append(f"  \\item {math_to_latex(step)}")
            # Interleave Chinese step below each English step
            if show_zh and j < len(sol_steps_zh):
                zh_step = sol_steps_zh[j]
                lines.append(f"  \\par {{\\footnotesize\\color{{textmuted}}{math_to_latex(zh_step)}}}")
        lines.append(r"\end{enumerate}")
        lines.append(r"}")

    # Common mistake — inline (no box) for compactness
    if mistake_en:
        lines.append(f"\\inlinemistake{{{math_to_latex(mistake_en)}}}")
        if show_zh and mistake_zh:
            lines.append(f"{{\\footnotesize\\color{{textmuted}}\\hspace{{4mm}}{math_to_latex(mistake_zh)}}}")


def _render_mcq_solution(q, num, lines):
    """Render solution for an MCQ question."""
    labels = "ABCDEFGH"
    explanation = q.get("explanation", "")
    correct_idx = q.get("correctAnswer", 0)
    options = q.get("options", [])

    lines.append(f"\\textbf{{Q{num}.}} ")

    if explanation:
        lines.append(math_to_latex(explanation))

    if 0 <= correct_idx < len(options):
        label = labels[correct_idx] if correct_idx < len(labels) else "?"
        lines.append(f"\\hfill \\textbf{{{label}}}")
    lines.append("")

    errors = q.get("common_errors", [])
    if errors:
        lines.append(r"\begin{mistakebox}")
        for err in errors:
            lines.append(f"\\textbullet\\ {math_to_latex(err)}\\\\")
        lines.append(r"\end{mistakebox}")


# ── Main content rendering ──────────────────────────────────────────────────

def render_content(data, out_path, lang="bilingual"):
    """Generate week_pack_content.tex with all sections."""
    show_zh = (lang == "bilingual")
    lines = []
    lines.append("% Auto-generated by render_week_pack.py — do not edit\n")

    core_q = data.get("questions_core", [])
    ext_q = data.get("questions_extended", [])
    total_marks = sum(get_marks(q) for q in core_q + ext_q)

    # ── Topic Overview ──
    lines.append(r"\SectionHeader{Topic Overview}")
    lines.append("")

    topic = data.get("topic", "")
    board = data.get("board", "CIE 0580")
    refs = data.get("syllabus_refs", [])

    lines.append(r"\begin{tcolorbox}[soft]")
    lines.append(r"\sffamily")
    lines.append(f"\\textbf{{Topic:}} {tex_escape(topic)}\\\\[1mm]")
    lines.append(f"\\textbf{{Board:}} {tex_escape(board)}\\\\[1mm]")
    if refs:
        lines.append(f"\\textbf{{Syllabus references:}} "
                      f"{tex_escape(', '.join(refs))}\\\\[1mm]")
    marks_display = str(total_marks) if total_marks > 0 else "---"
    lines.append(f"\\textbf{{Questions:}} {len(core_q)} Core + {len(ext_q)} Extended"
                  f" \\hfill \\textbf{{Total marks:}} {marks_display}")
    lines.append(r"\end{tcolorbox}")
    lines.append("")

    # ── Key Vocabulary (compact 2-column table) ──
    vocab = data.get("key_vocabulary", [])
    if vocab:
        lines.append(r"\SectionHeader[brand-dark]{Key Vocabulary}")
        lines.append("")

        # Render as compact 2-column multicol with small text
        lines.append(r"{\small")
        lines.append(r"\begin{multicols}{2}")
        lines.append(r"\raggedcolumns")
        for v in vocab:
            term = tex_escape(v.get("term_en", ""))
            zh = v.get("term_zh", "")
            defn = tex_escape(v.get("definition", ""))
            defn_zh = v.get("definition_zh", "")

            lines.append(r"\needspace{2\baselineskip}")
            if show_zh:
                lines.append(f"\\noindent\\textsf{{\\textbf{{{term}}}}} "
                              f"\\hfill {{\\scriptsize\\color{{gray}}{zh}}}\\\\")
            else:
                lines.append(f"\\noindent\\textsf{{\\textbf{{{term}}}}}\\\\")
            lines.append(f"{{\\footnotesize {defn}}}")
            if show_zh and defn_zh:
                lines.append(f"\\\\{{\\footnotesize\\color{{textmuted}}{defn_zh}}}")
            lines.append(r"\par\vspace{1.5mm}")
        lines.append(r"\end{multicols}")
        lines.append(r"}")
        lines.append("")

    # ── Core Questions ──
    if core_q:
        lines.append(r"\newpage")
        lines.append(r"\StudentStrip")
        lines.append(r"\SectionHeader[core-green]{Section A --- Core Questions}")
        lines.append("")
        render_questions(core_q, lines, start_num=1, section="core",
                         show_zh=show_zh)

    # ── Extended Questions ──
    if ext_q:
        lines.append(r"\bigskip")
        lines.append(r"\SectionHeader[ext-blue]{Section B --- Extended Questions}")
        lines.append("")
        render_questions(ext_q, lines, start_num=len(core_q) + 1,
                         section="extended", show_zh=show_zh)

    # ── Solutions (compact, smaller text) ──
    all_q = core_q + ext_q
    lines.append(r"\newpage")

    lines.append(r"\SectionHeader[brand-dark]{Solutions \& Worked Examples}")
    lines.append("")

    # Two-column solutions for compactness
    lines.append(r"\begin{multicols}{2}")
    lines.append(r"\raggedcolumns")
    render_solutions(all_q, lines, start_num=1, show_zh=show_zh)
    lines.append(r"\end{multicols}")

    # ── Review Checklist ──
    checklist = data.get("review_checklist", [])
    if checklist:
        lines.append(r"\vspace{4mm}")
        lines.append(r"\SectionHeader[core-green]{Review Checklist}")
        lines.append("")

        # Two-column checklist + self-assessment side by side
        lines.append(r"\begin{multicols}{2}")
        lines.append(r"\begin{itemize}[label=$\square$, leftmargin=6mm, itemsep=3mm]")
        for item in checklist:
            # Support both old string format and new {en, zh} format
            if isinstance(item, dict):
                item_en = item.get("en", "")
                item_zh = item.get("zh", "")
            else:
                item_en = item
                item_zh = ""
            lines.append(f"  \\item {tex_escape(item_en)}")
            if show_zh and item_zh:
                lines.append(f"  \\par {{\\footnotesize\\color{{textmuted}}{item_zh}}}")
        lines.append(r"\end{itemize}")
        lines.append(r"\columnbreak")
        lines.append("")
        lines.append(r"\noindent\textbf{Self-assessment:}")
        lines.append(r"\vspace{2mm}")
        lines.append(r"\begin{itemize}[label={}, leftmargin=0mm, itemsep=3mm]")
        if show_zh:
            lines.append(r"  \item $\square$ \textbf{Confident} — I can do these without help")
            lines.append(r"  \par {\footnotesize\color{textmuted}自信 — 我不需要帮助就能完成}")
            lines.append(r"  \item $\square$ \textbf{Needs practice} — I understand but make mistakes")
            lines.append(r"  \par {\footnotesize\color{textmuted}需要练习 — 我理解但会犯错}")
            lines.append(r"  \item $\square$ \textbf{Not sure} — I need to review this topic")
            lines.append(r"  \par {\footnotesize\color{textmuted}不确定 — 我需要复习这个主题}")
        else:
            lines.append(r"  \item $\square$ \textbf{Confident} — I can do these without help")
            lines.append(r"  \item $\square$ \textbf{Needs practice} — I understand but make mistakes")
            lines.append(r"  \item $\square$ \textbf{Not sure} — I need to review this topic")
        lines.append(r"\end{itemize}")

        # Link to exercises
        subtopic_ids = data.get("subtopic_ids", [])
        if subtopic_ids:
            exercise_key = subtopic_ids[0].replace(":", "-")
            url = f"https://www.25maths.com/exercises/{exercise_key}/"
            lines.append(r"\vspace{4mm}")
            lines.append(f"{{\\small\\sffamily\\noindent Practice online:\\par"
                          f"\\href{{{url}}}{{25maths.com/exercises}}}}")

        lines.append(r"\end{multicols}")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


# ── Entry point ─────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Render a week pack JSON file into LaTeX content files.")
    parser.add_argument("json_path",
                        help="Path to the week pack JSON file")
    parser.add_argument("--lang", choices=["en", "bilingual"],
                        default="bilingual",
                        help="Edition language: 'en' for English-only, "
                             "'bilingual' for English+Chinese (default: bilingual)")
    args = parser.parse_args()

    json_path = args.json_path
    if not os.path.isabs(json_path):
        json_path = os.path.join(REPO_ROOT, json_path)

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    os.makedirs(BUILD_DIR, exist_ok=True)

    vars_path = os.path.join(BUILD_DIR, "week_pack_vars.tex")
    content_path = os.path.join(BUILD_DIR, "week_pack_content.tex")

    render_vars(data, vars_path, lang=args.lang)
    print(f"  Generated: {vars_path}")

    render_content(data, content_path, lang=args.lang)
    print(f"  Generated: {content_path}")

    print(f"\n  Edition: {args.lang}")
    print(f"  Next: cd build && xelatex week_pack_template.tex")


if __name__ == "__main__":
    main()
