/*
  Auto-generated by scripts/member/sync_release_registry.js
  Source: _data/releases.json
*/
export const releaseRegistry = [
  {
    "release_id": "cie0580-free-vocab-bundle-2026w07",
    "version": "v1",
    "subtopic_id": "cie0580:number-c1:c1-01-types-of-number",
    "channels": [
      "payhip"
    ],
    "payhip_product_id": "5j2Sz",
    "payhip_url": "https://payhip.com/b/5j2Sz",
    "membership_tier": "",
    "asset_key": "",
    "status": "active"
  },
  {
    "release_id": "member-week01-algebra-foundations-2026w09",
    "version": "v1",
    "subtopic_id": "cie0580:algebra-c2:c2-01-introduction-to-algebra",
    "channels": [
      "member"
    ],
    "payhip_product_id": "{PRODUCT_ID}",
    "payhip_url": "https://payhip.com/b/{PRODUCT_ID}",
    "membership_tier": "active",
    "asset_key": "member-files/week01/algebra-foundations-pack.pdf",
    "status": "active"
  }
];

export function findReleaseById(releaseId) {
  return releaseRegistry.find((item) => String(item.release_id) === String(releaseId)) || null;
}
