/*
  Auto-generated by scripts/member/sync_release_registry.js
  Source: _data/releases.json
*/
export const releaseRegistry = [
  {
    "release_id": "cie0580-free-vocab-bundle-2026w07",
    "version": "v1",
    "subtopic_id": "cie0580:number-c1:c1-01-types-of-number",
    "channels": [
      "payhip"
    ],
    "payhip_product_id": "5j2Sz",
    "payhip_url": "https://payhip.com/b/5j2Sz",
    "membership_tier": "",
    "asset_key": "",
    "status": "active"
  },
  {
    "release_id": "member-week01-number-fdp-en-2026w10",
    "version": "v1",
    "subtopic_id": "cie0580:number-c1:c1-04-fractions-decimals-percentages",
    "channels": [
      "member"
    ],
    "payhip_product_id": "eN4l6",
    "payhip_url": "https://payhip.com/b/eN4l6",
    "membership_tier": "",
    "asset_key": "member-files/week01/week-01-en.pdf",
    "status": "active"
  },
  {
    "release_id": "member-week01-number-fdp-bilingual-2026w10",
    "version": "v1",
    "subtopic_id": "cie0580:number-c1:c1-04-fractions-decimals-percentages",
    "channels": [
      "member"
    ],
    "payhip_product_id": "eN4l6",
    "payhip_url": "https://payhip.com/b/eN4l6",
    "membership_tier": "",
    "asset_key": "member-files/week01/week-01-bilingual.pdf",
    "status": "active"
  },
  {
    "release_id": "member-week02-number-powers-indices-en-2026w11",
    "version": "v1",
    "subtopic_id": "cie0580:number-c1:c1-01-types-of-number",
    "channels": [
      "member"
    ],
    "payhip_product_id": "",
    "payhip_url": "",
    "membership_tier": "",
    "asset_key": "member-files/week02/week-02-en.pdf",
    "status": "active"
  },
  {
    "release_id": "member-week02-number-powers-indices-bilingual-2026w11",
    "version": "v1",
    "subtopic_id": "cie0580:number-c1:c1-01-types-of-number",
    "channels": [
      "member"
    ],
    "payhip_product_id": "",
    "payhip_url": "",
    "membership_tier": "",
    "asset_key": "member-files/week02/week-02-bilingual.pdf",
    "status": "active"
  }
];

export function findReleaseById(releaseId) {
  return releaseRegistry.find((item) => String(item.release_id) === String(releaseId)) || null;
}
