begin;

create table if not exists public.payhip_event_log (
  id bigint generated by default as identity primary key,
  provider_event_id text not null unique,
  provider text not null default 'payhip',
  event_type text not null,
  customer_email text,
  payload jsonb not null,
  processed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_payhip_event_log_processed_at
  on public.payhip_event_log (processed_at desc);

alter table public.payhip_event_log enable row level security;

commit;
