#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..', '..');
const sourcePath = path.join(root, '_data', 'releases.json');
const targetPath = path.join(root, 'functions', '_lib', 'release_registry.js');

function main() {
  if (!fs.existsSync(sourcePath)) {
    throw new Error(`Source file not found: ${sourcePath}`);
  }

  const raw = fs.readFileSync(sourcePath, 'utf8');
  const parsed = JSON.parse(raw);
  if (!Array.isArray(parsed)) {
    throw new Error('Expected _data/releases.json to be an array.');
  }

  const lines = [];
  lines.push('/*');
  lines.push('  Auto-generated by scripts/member/sync_release_registry.js');
  lines.push('  Source: _data/releases.json');
  lines.push('*/');
  lines.push('export const releaseRegistry = ' + JSON.stringify(parsed, null, 2) + ';');
  lines.push('');
  lines.push('export function findReleaseById(releaseId) {');
  lines.push("  return releaseRegistry.find((item) => String(item.release_id) === String(releaseId)) || null;");
  lines.push('}');
  lines.push('');

  fs.writeFileSync(targetPath, lines.join('\n'), 'utf8');
  process.stdout.write(`Synced release registry to ${targetPath}\n`);
}

main();
